// benchmark/web/vuejs/src/App.vue
<style>
.main-class {
  text-align: center;
  background-color: #f1f1f1;
  min-height: 100vh;
}

.App-header {
  display: flex;
  flex-direction: column;
  color: rgb(92, 92, 92);
  font-size: 1.3rem;
  min-width: 100vw;
  gap: 0.4rem;
}

.TextField {
  display: flex;
  /* min-height: 30vh; */
  max-width: 20vw;
  flex-direction: column;
  justify-content: center;
  /* gap: 10px; */
  margin: 0 auto;
  margin-top: 5vh;
}
</style>


<template>
  <main class="main-class">
    <header class="App-header">
      <p>Benchmark AREA - VueJS</p>
      <p>Elise PIPET - Grégoire LANTIM - Paul PARISOT - Esteban MARQUES - John DE KETTELBUTTER</p>
      <p>Temps de chargement : {{ loadTime }} ms</p>
    </header>
    <div class="TextField">
      <TextField label="Email"></TextField>
      <TextField label="Password"></TextField>
    </div>
  </main>
</template>

<script>
import TextField from './TextField.vue';

export default {
  components: {
    TextField
  },
  data() {
    return {
      loadTime: 0
    };
  },
  mounted() {
    const performance = window.performance;
    const loadTime = performance.now();
    this.loadTime = loadTime.toFixed(2); // Arrondir à 2 décimales
  }
}
</script>

// benchmark/web/react/src/App.js
import * as React from 'react';
import { useState, useEffect } from 'react';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

import './App.css';

function App() {
  const [loadTime, setLoadTime] = useState(0);

  useEffect(() => {
    const [navigation] = performance.getEntriesByType('navigation');
    if (navigation) {
      const loadTime = navigation.domContentLoadedEventEnd - navigation.startTime;
      setLoadTime(loadTime);
    }
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <p>Benchmark AREA - ReactJS</p>
        <p>Elise PIPET - Grégoire LANTIM - Paul PARISOT - Esteban MARQUES - John DE KETTELBUTTER</p>
        <p>Temps de chargement : {loadTime} ms</p>
      </header>
      <div className='TextField'>
        <Stack spacing={2} direction="column" className='TextField'>
            <TextField label="E-mail"/>
            <TextField label="Password"/>
        </Stack>
      </div>
      <div className='ConfirmButton'>
        <Button variant="contained" onClick={() => {alert('clicked');}}>
          Confirm
        </Button>
      </div>
    </div>
  );
}

export default App;
