// benchmark/web/vuejs/src/components/Home.vue
<template>
    <div class='Menu'>
        <Menu/>
    </div>
    <div class="div-techno">
        <img :src="reactJSLogo" class="img-techno" alt="React"/>
        <img :src="HTMLLogo" class="img-techno" alt="React"/>
        <img :src="VueJSLogo" class="img-techno" alt="React"/>
    </div>
  </template>

<style>
.Menu {
    text-align: center;
    margin-top: 1.3rem;
}

.div-techno {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1rem;
  margin-top: 20px;
}

.img-techno {
  width: 20vh;
  height: 20vh;
  background-color: white;
  border: 1px solid #ddd;
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  object-fit: cover;
  display: block;
  margin: auto;
  padding: 20px;
}
</style>

<script>
    import reactJS from '@/assets/web/reactjs.png';
    import HTML from '@/assets/web/html.png';
    import VueJS from '@/assets/web/vuejs.png';

    import Django from '@/assets/backend/django.png';
    import GO from '@/assets/backend/go.png';
    import NestJS from '@/assets/backend/nestjs.jpg';

    import MariaDB from '@/assets/database/mariadb.jpeg';
    import MySQL from '@/assets/database/mysql.png';
    import PostGres from '@/assets/database/postgres.png';
    import SQLite from '@/assets/database/sqlite.png';

    import Flutter from '@/assets/mobile/flutter.png';
    import Kotlin from '@/assets/mobile/kotline.png';
    import ReactNative from '@/assets/mobile/reactnative.png';
    
    import Menu from './Menu.vue'

    export default {
        name: 'Home',
        components: {
            Menu
        },
        data() {
            return {
                reactJSLogo: reactJS,
                HTMLLogo: HTML,
                VueJSLogo: VueJS,
                DjangoLogo: Django,
                GOLogo: GO,
                NestJSLogo: NestJS,
                MariaDBLogo: MariaDB,
                MySQLLogo: MySQL,
                PostGresLogo: PostGres,
                SQLiteLogo: SQLite,
                FlutterLogo: Flutter,
                KotlinLogo: Kotlin,
                ReactNativeLogo: ReactNative
            };
        }
    };
  </script>

// benchmark/web/react/src/Home.js
import React, { useState } from 'react';
import BasicMenu from './BasicMenu'

// Backend logos
import djangoLogo from './assets/backend/django.png'
import goLogo from './assets/backend/go.png'
import nestjsLogo from './assets/backend/nestjs.jpg'

// Database logos
import mariadbLogo from './assets/database/mariadb.jpeg'
import mysqlLogo from './assets/database/mysql.png'
import postgresLogo from './assets/database/postgres.png'
import sqliteLogo from './assets/database/sqlite.png'

// Web logos
import htmlLogo from './assets/web/html.png'
import reactjsLogo from './assets/web/reactjs.png'
import vuejsLogo from './assets/web/vuejs.png'

// Mobile logos
import flutterLogo from './assets/mobile/flutter.png'
import kotlinLogo from './assets/mobile/kotline.png'
import reactnativeLogo from './assets/mobile/reactnative.png'

function Home() {
    const [selectedCategory, setSelectedCategory] = useState('Web');
  
    const handleMenuClick = (category) => {
      setSelectedCategory(category);
    };
  
    const renderImages = () => {
      switch (selectedCategory) {
        case 'Backend':
          return (
            <div>
              <img src={djangoLogo} alt="Django Logo" />
              <img src={goLogo} alt="Go Logo" />
              <img src={nestjsLogo} alt="NestJS Logo" />
            </div>
          );
        case 'Database':
          return (
            <div>
              <img src={mariadbLogo} alt="MariaDB Logo" />
              <img src={mysqlLogo} alt="MySQL Logo" />
              <img src={postgresLogo} alt="Postgres Logo" />
              <img src={sqliteLogo} alt="SQLite Logo" />
            </div>
          );
        case 'Web':
          return (
            <div>
              <img src={htmlLogo} alt="HTML Logo" />
              <img src={reactjsLogo} alt="ReactJS Logo" />
              <img src={vuejsLogo} alt="VueJS Logo" />
            </div>
          );
        case 'Mobile':
          return (
            <div>
              <img src={flutterLogo} alt="Flutter Logo" />
              <img src={kotlinLogo} alt="Kotlin Logo" />
              <img src={reactnativeLogo} alt="React Native Logo" />
            </div>
          );
        default:
          return null;
      }
    };
  
    return (
      <div>
        <BasicMenu onClick={handleMenuClick} />
        {renderImages()}
      </div>
    );
  }

export default Home;
